version: "3"

networks:
  my_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management 
    ports:
      - "5672:5672"
    networks:
      - my_network

  user-service:
    image: user-service:latest
    ports:
      - "3000:3000"
    networks:
      - my_network

  product-service:
    image: product-service:latest
    ports:
      - "4001:4000"
    networks:
      - my_network

  order-service:
    image: order-service:latest
    ports:
      - "6000:6000"
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db  # You may change the volume path to your preference
    networks:
      - my_network


