name: Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Update to Node.js 18

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # User Service
      - name: User Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: user-service/package-lock.json
      - name: User Service - Install Dependencies
        run: npm install
        working-directory: ./user-service

      # Product Service
      - name: Product Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: product-service/package-lock.json
      - name: Product Service - Install Dependencies
        run: npm install
        working-directory: ./product-service

      # Order Service
      - name: Order Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: order-service/package-lock.json
      - name: Order Service - Install Dependencies
        run: npm install
        working-directory: ./order-service

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/CleanArchitecture-Microservice-Rabbitmq-CICD-Pipeline
            git rebase --abort
            rm -fr ".git/rebase-merge"
            git pull origin main
            cd ./user-service
            pm2 restart all
            cd ../product-service
            pm2 restart all
            cd ../order-service
            pm2 restart all
