name: Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Update to Node.js 18

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # User Service
      - name: User Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: user-service/package-lock.json
      - name: User Service - Install Dependencies
        run: npm install
        working-directory: ./user-service

      # Product Service
      - name: Product Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: product-service/package-lock.json
      - name: Product Service - Install Dependencies
        run: npm install
        working-directory: ./product-service

      # Order Service
      - name: Order Service - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: order-service/package-lock.json
      - name: Order Service - Install Dependencies
        run: npm install
        working-directory: ./order-service

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: List Contents of the Repository
        run: ls -al

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOSTS}},
          username: ${{secrets.USERS}},
          key: ${{secrets.KEYS}},
          port: ${{secrets.PORTS}},
          script: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            export NVM_DIR="${HOME}/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm install 18  # Update to Node.js 18
            npm install -g pm2
            cd /home/runner/work/CleanArchitecture-Microservice-Rabbitmq-CICD-Pipeline/CleanArchitecture-Microservice-Rabbitmq-CICD-Pipeline
            git pull origin main
            npm install
            npm start
